trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  SONARQUBE_PROJECT_KEY: "NodeApplication"
  SONARQUBE_SERVICE: "SonarQubeServiceConnection"
  SONAR_REPORT: "sonar-report.json"
  ZAP_REPORT: "zap_report.html"
  AZURE_STORAGE_ACCOUNT: "yourstorageaccount"
  AZURE_CONTAINER: "yourcontainer"

stages:
- stage: BuildAndScan
  jobs:
  - job: Job
    steps:
    # ✅ Checkout replaces GitClone
    - checkout: self
      displayName: 'Checkout repository'

    # ✅ SonarQube tasks (need SonarQube extension installed from Marketplace)
    - task: SonarQubePrepare@5
      inputs:
        SonarQube: $(SONARQUBE_SERVICE)
        scannerMode: 'CLI'
        configMode: 'manual'
        cliProjectKey: $(SONARQUBE_PROJECT_KEY)
        cliSources: '.'

    - task: SonarQubeAnalyze@5

    - task: SonarQubePublish@5
      inputs:
        pollingTimeoutSec: '300'

    # Export Sonar report
    - script: |
        curl -u admin:$(SONAR_TOKEN) \
          "http://<your-sonarqube-url>/api/issues/search?projectKeys=$(SONARQUBE_PROJECT_KEY)" \
          > $(SONAR_REPORT)
      displayName: 'Export Sonar Report'

    # Run OWASP ZAP
    - script: |
        docker run -v $(System.DefaultWorkingDirectory):/zap/wrk/:rw \
          ghcr.io/zaproxy/zaproxy:stable zap-baseline.py \
          -t http://<your-azure-vm-ip>:8000 \
          -r $(ZAP_REPORT) \
          -m 5
      displayName: 'Run OWASP ZAP Scan'

    # Upload ZAP Report to Azure Blob
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'MyAzureConnection'   # Make sure this service connection exists
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az storage blob upload \
            --account-name $(AZURE_STORAGE_ACCOUNT) \
            --container-name $(AZURE_CONTAINER) \
            --name $(ZAP_REPORT) \
            --file $(ZAP_REPORT) \
            --auth-mode key
      displayName: 'Upload ZAP Report to Azure Blob'

    # ✅ Email notification handled outside pipeline
    # Remove Mailer task – use Azure DevOps Notifications instead
