name: Deploy MyProject

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      # ❌ OLD ZAP SCAN step (remove it)
      # - name: Run ZAP Scan
      #   uses: aws-actions/s3-sync-action@v0.5.1   <-- this was wrong

      # ✅ REPLACE WITH THIS
      - name: Run OWASP ZAP Scan
        run: |
          mkdir -p zap-report
          docker run --rm \
            -v $(pwd)/zap-report:/zap/wrk:rw \
            ghcr.io/zaproxy/zaproxy:stable \
            zap-full-scan.py -t http://184.169.251.147:8082 -r zap_report.html

      - name: Upload ZAP report to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks
        env:
          AWS_S3_BUCKET: niraj-1588
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'ap-south-1'
          SOURCE_DIR: zap-report
