version: '3.8'

services:
  web:
    image: nginx:alpine
    container_name: myproject_web
    ports:
      - "8080:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./:/usr/share/nginx/html
    restart: always
