name: Deploy to EC2

on:
  push:
    branches:
      - main   # change to your branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Start SSH Agent
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@184.169.251.147 "
            cd ~/myproject &&
            docker-compose down &&
            docker-compose up -d
          "
