name: CI with Sonar + OWASP ZAP + S3 + Email

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Set up JDK 17 (required by Sonar)
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # 3. SonarCloud Scan
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          args: >
            -Dsonar.projectKey=iamnrj_1588
            -Dsonar.organization=iamnrj1588
            -Dsonar.sources=.
            -Dsonar.branch.name=main
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: https://sonarcloud.io

      # 4. Run OWASP ZAP Baseline Scan
      - name: Run OWASP ZAP Scan
        run: |
          mkdir zap-report
          docker run --rm -v $(pwd)/zap-report:/zap/wrk \
            ghcr.io/zaproxy/zaproxy:stable \
            zap-baseline.py -t http://184.169.251.147:8082 -r zap_report.html

           # 5. Upload ZAP Report to S3
      - name: Upload ZAP Report to S3
        uses: aws-actions/s3-sync-action@v1
        with:
          args: --acl public-read --follow-symlinks
        env:
          AWS_S3_BUCKET: niraj-1588
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ap-south-1   # change if bucket is in another region
          SOURCE_DIR: ./zap-report
